### PR TITLE
Turtlecoin Status Badges

### PR DESCRIPTION
**Pull request by KosnIre**
## Summary
Added new Turtlecoin-branded status badges in .svg format, as well as Affinity Designer source file. These can be used to create dynamic information, shown in GitHub repo README files. For example, a badge that shows `"Network: {Online | Offline| Provisioning}"`

## Status
READY FOR REVIEW

## CHANGES
- Added Affinity Designer source file, with exported .svg files
- Added a Design Guide in .png format that shows badge layouts and hex color values
- Added a sample .png image of existing badge variants
- Added a Python script that will change exported .svg files from height=100% to height=20px

### CODE REVIEW

**Comment by SoreGums** [comment]
This is great: 💯 

I'm going to tweak things to what will actually be used on the status badges, so anyone who has commit bits, hold off until I do that please 🙇

**Comment by SoreGums** [comment]
how come those SVG file shadows are off by a lot?

image

**Comment by SoreGums** [comment]
hmm, looks like it is because the text is being exported as an image instead of outlines or font/text :/

**Comment by RocksteadyTC** [comment]
?

**Comment by ExtraHash** [comment]
looks sweet

**Pull request merged**
